### ISSUE TITLE
Shipshape

### ISSUE THREAD

**Issue by northeastprince** [basecamp/handbook#111]
Is Shipshape going to be open-source anytime soon? Also, why does Basecamp only use Apple computers?

**Comment by onerinas** [comment]
What’s shipshape?

**Comment by northeastprince** [comment]
Their employee security protocol monitoring software.
<https://github.com/basecamp/handbook/blob/master/our-internal-
systems.md>

On February 6, 2022, Matt ***@***.***> wrote:
> What’s shipshape?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/basecamp/handbook/issues/111#issuecomment-
1030919854>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ANE36NCJRVM77KTPNNFBAH3UZ3S6LANCNFSM5NSZMSKA>.
You are receiving this because you authored the thread.Message ID:
***@***.***>
