### ISSUE TITLE
Titles for areas like sales and marketing

### ISSUE THREAD

**Issue by rapcal** [basecamp/handbook#157]
Basecamp has always been an inspiration for me management-wise. So when I decided to finally write down a handbook for our company, yours became one of the first benchmarks.

One thing that I couldn't understand though was why you chose not to include role guidelines for areas like sales, marketing or customer success.

**Comment by jeremy** [comment]
See e.g. https://github.com/basecamp/handbook/blob/44b5891d20b8ccf0806d59cffb2a85f5d3ed307b/titles-for-support.md
