### ISSUE TITLE
Missing word?

### ISSUE THREAD

**Issue by CdrMarks** [basecamp/handbook#16]
This sentence under [Org Chart > Ops](https://github.com/basecamp/handbook/blob/master/orgchart.md#qa) seems to be missing a word or two:
> They run rolling tests all web and mobile versions of Basecamp for quality control.

**Comment by blakestoddard** [comment]
It took me a second to figure out that you were actually referring to the QA section of the Org Chart page. Fixed in [PR 19.](https://github.com/basecamp/handbook/pull/19)

**Comment by CdrMarks** [comment]
The edit looks good.  I think the commit message should reference orgchart->QA though.

**Comment by blakestoddard** [comment]
Yep, you're right. Fixed (though my amend didn't quite work as I expected) and [merged](https://github.com/basecamp/handbook/commit/02d9ef922ed0ab6311130c1c2fe1dc3207ae4efe).
