### ISSUE TITLE
Campfire history suggests new signups are possible

### ISSUE THREAD

**Issue by hayesr** [basecamp/handbook#27]
The last sentence of the [Campfire history reads](https://github.com/basecamp/handbook/blob/master/product-histories.md#campfire):

> Customers can still sign up for an independent Campfire account (they don’t need to be a Basecamp customer), so /play loggins can continue to amuse people indefinitely.

[But that doesn't seem to be accurate](https://basecamp.com/retired/campfire). Does customer-not-Basecamp-customer mean a Backpack, Highrise, _et al_ customer?

**Comment by georgeclaghorn** [comment]
Thanks!
