### ISSUE TITLE
Hearbeats Question

### ISSUE THREAD

**Issue by sundarv85** [basecamp/handbook#32]
Hello,

In https://github.com/basecamp/handbook/blob/master/how-we-work.md#heartbeats

there are links for "daily questions", "weekly questions" and "team updates". Is there any format that you are using? If yes, it would be helpful if that can be clarified.

**Comment by jeremy** [comment]
Hi! No specific format is requested or required. We're all aiming to keep each other in the loop, but it's up to everyone to choose what to share and how to communicate.

For example, daily updates may take the form of a quick bullet point rundown, a short narrative, a deeper write-up of something particularly interesting that came up, or an announcement or celebration. What's important is that we're considering what's salient and sharing it consistently.
