### ISSUE TITLE
Shipshape

### ISSUE THREAD

**Issue by pawelorzech** [basecamp/handbook#33]
In https://github.com/basecamp/handbook/blob/master/getting-started.md you're mentioning [Shipshape. 
](https://github.com/basecamp/shipshape/)
Is there any chance to know what's in there? Or make it public just like this handbook?

**Comment by kimroen** [comment]
This has been [asked and answered a few times already](https://github.com/basecamp/handbook/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20shipshape). The gist of it is this (from https://github.com/basecamp/handbook/issues/28#issuecomment-299650344):

> Shipshape is a "low touch," unintrusive security auditor for macOS. It's implemented as a [Bats](https://github.com/sstephenson/bats) test suite and it pushes test results to a git repos. Failing tests mention the user, causing GitHub to alert them. This was built to be open source, so that'll (eventually) fix the private link 😊

Hope that helps!

**Comment by pawelorzech** [comment]
Yay!

Yes, thank you! 👍
