### ISSUE TITLE
$ 1,000 home office expense

### ISSUE THREAD

**Issue by imam** [basecamp/handbook#41]
This handbook rocks! 🎸 I'm surely will use this as my company's benefit guideline later in the future😊

But however, I'm noticing that you'll give to your employee $ 1,000 for their home office every 3 years. Is it goes to new comers too? You'll give $ 1,000 right after you hire them?

**Comment by javan** [comment]
Yes, it applies to all employees. It's not like you're given $1,000 cash though. You can expense up to $1,000 to furnish your home office and create a comfortable working environment.
