### ISSUE TITLE
What is `Deep expertise` mean?

### ISSUE THREAD

**Issue by ugtkbtk** [basecamp/handbook#42]
At page of [Titles for programmers](https://github.com/basecamp/handbook/blob/master/titles-for-programmers.md), on line [27](https://github.com/basecamp/handbook/blame/master/titles-for-programmers.md#L27), what is example of `Deep expertise` ?
And please tell us the example of it at Basecamp.

**Comment by jeremy** [comment]
> Deep expertise within at least one programming environment.

Another way to say this: Full grasp and command of the language. Fluency.

Examples of this: Making lucid, aesthetic judgements about code, from design to implementation and style. Writing code that's a pleasure for others to read and *understand*.

**Comment by ugtkbtk** [comment]
@jeremy Thank you!
