### ISSUE TITLE
Suggestion: International travel dead person’s switch

### ISSUE THREAD

**Issue by Zyber17** [basecamp/handbook#43]
It's not super clear if you all are open to outside suggestions, so sorry if this is unwanted. Anyhow…

In the [International Travel Guide](https://github.com/basecamp/handbook/blob/master/international-travel-guide.md) you suggest:
> If you're detained or encounter some other serious customs headache, contact our attorney directly: Jennifer Pflanz (get phone number from Andrea). Customs and Border Protection (CBP) is not required to allow you to contact an attorney, but Jennifer is your first call if possible.

Instead, I would suggest (and I'm pretty sure this is an idea I stole from [CGP Grey](https://twitter.com/cgpgrey)) whenever you travel to a country where you'll have to go through CBP, upon landing — but before going through customs or even deplaning — message some trusted person(s) letting them know you've landed at YYY airport and that you'll be going through customs soon, and to call the lawyer if they don't receive a message from you saying that you've cleared customs in the next _X_ hours (where _X_ is some reasonable number). That way, if things go really poorly, you know at the very least that legal help is on the way.

**Comment by jeremy** [comment]
Great suggestion @Zyber17. Thank you. We do this informally, but with weekend travel to meetups with lots of staff traveling it hasn't felt practical to institutionalize.
