### ISSUE TITLE
Update Highrise section

### ISSUE THREAD

**Issue by simonista** [basecamp/handbook#54]
Hey all, love what you're doing, thanks for making this resource public to help others get insight into how you run things.

Was just going through it after watching a GettingReal video, and noticed that [the highrise section](https://github.com/basecamp/handbook/blob/master/product-histories.md#highrise) needs to be updated in light of the recent closure to new signups.

Thanks again!

**Comment by dhh** [comment]
Thanks for the prodding! I've updated the section in https://github.com/basecamp/handbook/commit/e492a893e37bba2479f9f89859712808523882fd.
