### ISSUE TITLE
judgment instead of judgement

### ISSUE THREAD

**Issue by pencoyd** [basecamp/handbook#6]
Not sure if you want PRs for that small typo, which appears a few times in this file.

**Comment by shaneog** [comment]
Basecamp is based in the US, so would use the American English spelling: http://grammarist.com/spelling/judgment-judgement/

**Comment by pencoyd** [comment]
@shaneog the article you point to says "In American English, judgement is generally considered a misspelling of judgment for all uses of the word, notwithstanding individual preferences."

Hardly matters: just appreciative that this resource was shared with us all, and noticed this little niggle.

**Comment by shaneog** [comment]
@pencoyd My sincere apologies. I misread your initial issue 😞
