### ISSUE TITLE
Why do you use absolute paths in README.md

### ISSUE THREAD

**Issue by erusev** [basecamp/handbook#60]
You can use this:

```md
[What We Stand For](what-we-stand-for.md)
```

instead of:

```md
[What We Stand For](https://github.com/basecamp/handbook/blob/master/what-we-stand-for.md)
```

and the links would still work.

I'm working on a piece of content that I want to publish on GitHub and I like your approach, but I don't understand the absolute paths. It'd be great if you clarified this for me.

Thanks!

**Comment by jeremy** [comment]
No reason! We should switch to relative URLs 😊
