### ISSUE TITLE
Monthly coworking space stipend amount different on Jobs page

### ISSUE THREAD

**Issue by boostventilator** [basecamp/handbook#72]
I was just researching for a job application and noticed the monthly coworking space stipend amount differs in this handbook compared to what is currently being listed on the [Basecamp Jobs page](https://basecamp.com/about/jobs):

<img width="380" alt="Work_at_Basecamp" src="https://user-images.githubusercontent.com/194032/60622075-cf0eb600-9db5-11e9-81a6-e00bbcbfe9cd.png">

> Coworking Space Stipend - Don't feel like working from home? No sweat. Basecamp will pay up to $100/month towards renting co-working space in your city.

https://basecamp.com/about/jobs

> **From a coworking space**
> 
> If working from home or from a coffee shop doesn't suit you, then trying a coworking space might just do the trick. Basecamp offers a $200/month stipend towards a desk in such a place.

https://github.com/basecamp/handbook/blob/master/where-we-work.md

> **Coworking Space Stipend**
> 
> Basecamp will pay up to $200/month for you to use towards renting coworking space in your city. Please make sure you're using a true coworking space that's meant solely for working, not a club or social space.

https://github.com/basecamp/handbook/blob/master/benefits-and-perks.md

**Comment by javan** [comment]
$200 is the correct amount. It was changed from $100 in https://github.com/basecamp/handbook/commit/bca65c83e85b2cce1468a3fa681452e151651f74. @vampeel, can you update https://basecamp.com/about/jobs, please?

**Comment by vampeel** [comment]
Fixed. Thanks for the heads up @boostventilator .
