### ISSUE TITLE
[our-internal-systems] - 404 on some GitHub links

### ISSUE THREAD

**Issue by AdrienFromToulouse** [basecamp/handbook#73]
Hi there,

I noticed a couple of `404` on this page: https://github.com/basecamp/handbook/blob/master/our-internal-systems.md

Namely:

- https://github.com/basecamp/37
- https://github.com/basecamp/shipshape

Would have happily made a PR but cannot find the correct links.

Cheers,

**Comment by georgeclaghorn** [comment]
They’re private repositories.
