### ISSUE TITLE
better ops team name

### ISSUE THREAD

**Issue by SimonElNahasChristensen** [basecamp/handbook#77]
I think they could have a more clear name. 
There is Dev ops, Biz Ops and more being emerging buzzwords.
I see that it makes sense in the context of COO, but I just wanted to give you this feedback that i felt when reading it through. 

If the name was to change, what ideas do you have for a better name?

I'm not working in basecamp but i think your handbook gives a view into a great and fascinating work culture. 

Best Regards 
Simon
A computer science student reading about interesting stuff

**Comment by jeremy** [comment]
There are many kinds of operations—including our People Ops team! On our org chart, it's spelled out as Technical Operations. But we usually just say "Ops!" as a shorthand name that suits our strong focus on technical operations and systems administration.

Thanks for your input, Simon!
