### ISSUE TITLE
Shipshap link leads to 404

### ISSUE THREAD

**Issue by dstergiou** [basecamp/handbook#80]
Hey,

the document at https://github.com/basecamp/handbook/blob/master/our-internal-systems.md mentions ShipShape, but the link points to a 404 page. Do you have any plans to make ShipShape available?

**Comment by javan** [comment]
We hope to!. No ETA. See also: 
- https://github.com/basecamp/handbook/issues/28#issuecomment-299650344
- https://github.com/basecamp/handbook/issues?q=is%3Aissue+shipshape+is%3Aclosed
✌️
