### ISSUE TITLE
Global Entry links to a dead page

### ISSUE THREAD

**Issue by oleoneto** [basecamp/handbook#81]
**Global Entry** links to https://help.cbp.gov/app/answers/detail/a_id/1035/~/global-entry-program---who-can-apply, which seems to be an invalid page on CBP's website.

**Comment by jeremy** [comment]
Nice catch @oleoneto! Do you have a current link?

**Comment by oleoneto** [comment]
Hey @jeremy, I'm finding it hard to recognize the most appropriate link as I do not know the content of the original one. However, the following link seems to answer most questions on the topic:
https://www.cbp.gov/travel/trusted-traveler-programs/global-entry/frequently-asked-questions

**Comment by jeremy** [comment]
Thanks @oleoneto! Updated.
