### ISSUE TITLE
Minor link corrections

### ISSUE THREAD

**Issue by vanmash** [basecamp/handbook#91]
Hey

a couple of minor link corrections:

1. [repo's](https://github.com/basecamp/handbook) website (to the right of Description) should be "https://basecamp.com/handbook"

2. KnowYourCompany is KnowYourTeam now
https://basecamp.com/handbook/05-product-histories#know-your-company
https://knowyourcompany.com/story -- > https://knowyourteam.com/m/story

3. A few 🔒  for private links are missing

- https://basecamp.com/handbook/07-where-we-work#from-coffee-shops
please do mind our **basic security rules**

- https://basecamp.com/handbook/08-benefits-and-perks#expense-account
you can find those in **Basecamp**! 

- https://basecamp.com/handbook/11-our-rituals#meetups
**Here are some tips from Basecamp teammates about Meetups**

- https://basecamp.com/handbook/11-our-rituals#mini-meetups
Budget guidelines for mini meet-ups can be found **in Basecamp**.

- https://basecamp.com/handbook/appendix-07-code-of-conduct#enforcement
Or you can complete a **complaint form**.

4. https://basecamp.com/handbook/09-getting-started#your-buddy
Even when you know **who does what** should link to https://basecamp.com/handbook/06-orgchart

best,
Maciek

**Comment by janejuenyang** [comment]
Thanks Maciek! I updated Know Your Team. The private links are intentionally private and for now keeping the repo’s connected website to the link about Basecamp-the-company writ large since basecamp.com/handbook is a copy of this repo and doesn’t give much additional context for this handbook whereas the About page does.
