### ISSUE TITLE
Ta-da's retirement was in 2012 not 2014

### ISSUE THREAD

**Issue by fm** [basecamp/handbook#92]
In the [Product Histories](https://github.com/basecamp/handbook/blob/master/product-histories.md) section it says Ta-da closed to new signups in 2014, but [DHH's post in SvN](https://signalvnoise.com/posts/3830-ta-da-list-until-the-end-of-the-internet) says 2012. May be worth checking and correcting.

**Comment by janejuenyang** [comment]
Good catch - just fixed. Thanks for reporting!
