### ISSUE TITLE
Make internal links target to url where content it's shown in it's full glory.

### ISSUE THREAD

**Issue by Bartmax** [basecamp/handbook#95]
I was reading the basecamp handbook for researching purposes and I noticed a weird and distracting behavior when clicking on links (in the content as opposed to on the sidebar) as the links pointed straight to github.

After some investigation I found that indeed the content is supported inside the handbook domain on it's full glory but the .md address is only converted in the navigation menu and not inside the content of a page (or at least, that's what it seems).

This clearly distracted me enough from my read and I believe it would be more pleasant for the casual reader to stay within the site and be able to get the benefit of the copy and style on the site instead of github.

I wasn't able to find where the actual process of the links resides, I believe it's kept internal, otherwise I will be glad to be pointed to it if you believe that providing a PR will be of any value to the project.

Example:
_(note: this is just one of many, all appendix links that appears in a page content shows the same behavior)_

**Where the link points to in the actual content:**

<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/3386797/98382102-83af8c00-2029-11eb-804f-376b3e827a4a.png"><img width="750" src="https://user-images.githubusercontent.com/3386797/98382102-83af8c00-2029-11eb-804f-376b3e827a4a.png" alt="image" style="max-width:100%;"></a>

----------------------------------

**The url in handbook full glory:**

<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/3386797/98381969-5662de00-2029-11eb-9391-9ccb304e4950.png"><img width="546" src="https://user-images.githubusercontent.com/3386797/98381969-5662de00-2029-11eb-9391-9ccb304e4950.png" alt="image" style="max-width:100%;"></a>

**Comment by janejuenyang** [comment]
Thanks for the note @Bartmax! The double-edged sword of making our handbook public is it added some additional maintenance responsibility for our small team. 😅 Tagging in @vampeel for an FYI but for transparency purposes, we won't be able to prioritize updating the internal links in the near future.

**Comment by vampeel** [comment]
This is fixed now, thanks for raising the issue @Bartmax.

**Comment by Bartmax** [comment]
Your handbook served me as great inspiration and I really appreciate that it is public.
I also confirm the fix is solid! Amazing job 👍, and thanks again for having this content public.
