### ISSUE TITLE
What is the license for the handbook?

### ISSUE THREAD

**Issue by GuiSim** [basecamp/handbook#98]
I'm a fan of Basecamp's employee handbook and would like to use parts of it at Capdesk.
What is the license on the content of this repository?

Thank you!

**Comment by QWp6t** [comment]
x-ref #5 #82

**Comment by GuiSim** [comment]
Thank you!

Considering this has been asked a few times already, I'd suggest putting
that information somewhere, perhaps in a license file?

**Comment by janejuenyang** [comment]
Thanks @GuiSim and @QWp6t! This conversation prompted us to have another conversation on this topic and check in on the latest thinking. I just pushed up a note on what's permitting re: inspiration from our handbook. https://github.com/basecamp/handbook/commit/8eb30ba4cf96afd4b551bd34e055ec325a919f85
